### ISSUE TITLE
Warcarrier fails to run on Arch Linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [weaknetlabs/warcarrier#1]
```
What steps will reproduce the problem?
1. Install all dependencies
2. Put interface in monitor mode and GPS device in NMEA mode
3. Run Warcarrier application

What is the expected output? What do you see instead?

I expect the output seen here -> http://warcarrier.org/images/wc.gif
Instead the application opens, sits for a second, and then closes with 
absolutely no error messages or anything useful for debugging.


What version of the product are you using? On what operating system?

Happens on both Warcarrier 0.3.04 and the revision 56 from subversion
Using Arch Linux

Please provide any additional information below.
```

Original issue reported on code.google.com by `grant.c....@gmail.com` on 27 Oct 2013 at 12:38

**Comment by RackunSec** [comment]
This issue can be caused by many things. I would test your GPSD using XGPS first. If it is working, please make sure that the log directories exist, such as "./logs/pcap" specifically as Perl does not chack that yet in my code. Also, make sure your wireless device can sniff in RFMON with Airdoump-NG. You can also run WARCARRIER manually by starting Airodump-NG with the "--write (filename)" argument and pass that file into WARCARRIER.
