### ISSUE TITLE
Fails To Start

### ISSUE THREAD

**Issue by ghost** [weaknetlabs/warcarrier#2]
I am trying to use Warcarrier on Debian. All dependencies are installed. Warcarrier starts up with no errors, says it's initializing, and then simply quits. It gives no errors upon quiting - so sadly I have no error messages to provide you. Do you know (or have a guess) as to what the issue could be? I have an Alfa AWUS036H wireless adapter and monitor mode and injection work flawlessly for all other programs I've used it for. I also have a GPS device that I used when the Warcarrier project was in beta, and Warcarrier worked great with my GPS device at that time. The only thing I don't have is a bluetooth device - which I am not concerned with. I have no plans for bluetooth hacking. Thank you for your time Douglas (Trev).

**Comment by RackunSec** [comment]
Hello, Yeah I am not sure why Perl's version of curses doesn't give any errors to stderr. What you can do is manually test your devices with gpspipe for GPS and airmon-ng/airodump-ng for WiFi devices. If they are running fine, then you should have no problem with WARCARRIER unless your software version of the dependencies have changed dramatically. If the above manual tests work, I would simply recommend trying it in WT7 as I have personally/specifically compiled/set up all of the dependencies for WARCARRIER to work in the ISO. Let me know how it turns out!

**Comment by ghost** [comment]
Thank you for your quick response, sir. It turns out that my Alfa adapter was dead. So when I tested it again with my other working Alfa adapter, everything went smoothly, once I opened my terminal to a large enough size. Just a suggestion - you should put the minimum size required for it to display properly. Anyways, much love to your and your work Trev. I will be closing this issue now that I know it was my own hardware's fault, not your awesome coding.
